{{- if .Values.vault.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-vault
  labels:
    {{- include "cong-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    {{- include "cong-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-vault
  labels:
    {{- include "cong-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault
spec:
  replicas: {{ .Values.vault.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "cong-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: vault
  template:
    metadata:
      labels:
        {{- include "cong-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: vault
    spec:
      serviceAccountName: {{ include "cong-chart.fullname" . }}
      containers:
        - name: vault
          image: "{{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vault.image.pullPolicy }}
          {{- with .Values.vault.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - "vault"
          args:
            - "server"
            - "-dev"
          securityContext:
            capabilities:
              add:
                - "IPC_LOCK"
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "cong-chart.fullname" . }}-vault-secrets
                  key: root-token
          ports:
            - containerPort: 8200
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-vault-secrets
type: Opaque
data:
  root-token: {{ .Values.vault.rootToken | b64enc }}
{{- end }}